import { RadioExample as RadioGroupExample } from "./usage-examples/radio-group";
import { SidebarExample, NavigationItemExample } from "./examples/sidebar";
import { StatusMeterExample, CarouselExample } from "./examples/default-web";
import {
  ChatExample,
  IconExample,
  IconButtonExample,
  ListExample,
} from "./examples/default-web";
import type { ComponentType } from "react";
import {
  AutocompleteExample,
  ButtonExample,
  CheckboxExample,
  CheckboxGroupExample,
  ComboboxExample,
  FieldExample,
  FieldsetExample,
  FormExample,
  InputExample,
  NumberFieldExample,
  OTPExample,
  RadioExample,
  SelectExample,
  SliderExample,
  SwitchExample,
  TextareaExample,
} from "./examples/forms";
import {
  AlertDialogExample,
  ContextMenuExample,
  DialogExample,
  DrawerExample,
  MenuExample,
  PopoverExample,
  PreviewCardExample,
  ToastExample,
  TooltipExample,
} from "./examples/overlays";
import {
  AccordionExample,
  BreadcrumbExample,
  CollapsibleExample,
  MenubarExample,
  NavigationMenuExample,
  TabsExample,
  ToggleExample,
  ToggleGroupExample,
  ToolbarExample,
} from "./examples/navigation";
import {
  AlertExample,
  AvatarExample,
  BadgeExample,
  CardExample,
  EmptyExample,
  MeterExample,
  ProgressExample,
  ScrollAreaExample,
  SeparatorExample,
  SkeletonExample,
  TableExample,
  TypographyExample,
} from "./examples/display";

export type CatalogEntry = {
  id: string;
  name: string;
  group: string;
  description: string;
  Example: ComponentType;
  primitive: boolean;
};
export const catalog: CatalogEntry[] = [
  {
    id: "sidebar",
    name: "Sidebar",
    group: "Default 웹",
    description:
      "Roblox 홈의 탐색 구조. NavigationItem·Icon·ScrollArea와 모바일 Dialog를 조합합니다.",
    Example: SidebarExample,
    primitive: true,
  },
  {
    id: "navigation-item",
    name: "Navigation Item",
    group: "Default 웹",
    description:
      "40px 탐색 행. 링크·버튼·아이콘·배지를 원하는 화면에서 재사용합니다.",
    Example: NavigationItemExample,
    primitive: true,
  },
  {
    id: "status-meter",
    name: "Status Meter",
    group: "Default 웹",
    description: "Account Status의 4칸 상태 표시와 카드.",
    Example: StatusMeterExample,
    primitive: true,
  },
  {
    id: "carousel",
    name: "Carousel",
    group: "Default 웹",
    description: "가로 카드 컬렉션. Base UI ScrollArea와 버튼 조합.",
    Example: CarouselExample,
    primitive: true,
  },
  {
    id: "chat",
    name: "Chat",
    group: "Default 웹",
    description: "새 Chat과 그룹 패널. 가상 데이터, 원본 치수, Base UI 조합.",
    Example: ChatExample,
    primitive: true,
  },
  {
    id: "icon",
    name: "Icon",
    group: "Default 웹",
    description: "배포 CSS에서 확인한 38개 Roblox glyph.",
    Example: IconExample,
    primitive: false,
  },
  {
    id: "icon-button",
    name: "Icon Button",
    group: "Default 웹",
    description: "원형·사각 아이콘 버튼. 4개 크기와 5개 역할.",
    Example: IconButtonExample,
    primitive: true,
  },
  {
    id: "list",
    name: "List",
    group: "Default 웹",
    description: "Security와 Plus에서 확인한 목록 구조와 간격.",
    Example: ListExample,
    primitive: true,
  },
  {
    id: "button",
    name: "Button",
    group: "입력과 선택",
    description: "9가지 action 역할과 4가지 크기의 버튼.",
    Example: ButtonExample,
    primitive: true,
  },
  {
    id: "checkbox",
    name: "Checkbox",
    group: "입력과 선택",
    description: "단일 항목의 선택과 해제.",
    Example: CheckboxExample,
    primitive: true,
  },
  {
    id: "checkbox-group",
    name: "Checkbox Group",
    group: "입력과 선택",
    description: "Checkbox Group의 조합 가능한 사용 예제.",
    Example: CheckboxGroupExample,
    primitive: true,
  },
  {
    id: "switch",
    name: "Switch",
    group: "입력과 선택",
    description: "즉시 적용되는 켜기 · 끄기 설정.",
    Example: SwitchExample,
    primitive: true,
  },
  {
    id: "input",
    name: "Input",
    group: "입력과 선택",
    description: "Input의 조합 가능한 사용 예제.",
    Example: InputExample,
    primitive: true,
  },
  {
    id: "textarea",
    name: "Textarea",
    group: "입력과 선택",
    description: "Textarea의 조합 가능한 사용 예제.",
    Example: TextareaExample,
    primitive: false,
  },
  {
    id: "field",
    name: "Field",
    group: "입력과 선택",
    description: "Field의 조합 가능한 사용 예제.",
    Example: FieldExample,
    primitive: true,
  },
  {
    id: "form",
    name: "Form",
    group: "입력과 선택",
    description: "필드 검증과 제출 상태를 함께 다룹니다.",
    Example: FormExample,
    primitive: true,
  },
  {
    id: "fieldset",
    name: "Fieldset",
    group: "입력과 선택",
    description: "Fieldset의 조합 가능한 사용 예제.",
    Example: FieldsetExample,
    primitive: true,
  },
  {
    id: "select",
    name: "Select",
    group: "입력과 선택",
    description: "정해진 옵션 중에서 선택합니다.",
    Example: SelectExample,
    primitive: true,
  },
  {
    id: "combobox",
    name: "Combobox",
    group: "입력과 선택",
    description: "검색과 선택을 한 입력에서 처리합니다.",
    Example: ComboboxExample,
    primitive: true,
  },
  {
    id: "autocomplete",
    name: "Autocomplete",
    group: "입력과 선택",
    description: "추천 항목을 참고하며 자유롭게 입력합니다.",
    Example: AutocompleteExample,
    primitive: true,
  },
  {
    id: "radio",
    name: "Radio",
    group: "입력과 선택",
    description: "Radio의 조합 가능한 사용 예제.",
    Example: RadioExample,
    primitive: true,
  },
  {
    id: "radio-group",
    name: "Radio Group",
    group: "입력과 선택",
    description: "Radio Group의 조합 가능한 사용 예제.",
    Example: RadioGroupExample,
    primitive: true,
  },
  {
    id: "slider",
    name: "Slider",
    group: "입력과 선택",
    description: "연속된 숫자 범위의 값을 조절합니다.",
    Example: SliderExample,
    primitive: true,
  },
  {
    id: "number-field",
    name: "Number Field",
    group: "입력과 선택",
    description: "Number Field의 조합 가능한 사용 예제.",
    Example: NumberFieldExample,
    primitive: true,
  },
  {
    id: "otp-field",
    name: "Otp Field",
    group: "입력과 선택",
    description: "Otp Field의 조합 가능한 사용 예제.",
    Example: OTPExample,
    primitive: true,
  },
  {
    id: "dialog",
    name: "Dialog",
    group: "레이어와 피드백",
    description: "작업에 집중하는 모달. 포커스와 Escape를 관리합니다.",
    Example: DialogExample,
    primitive: true,
  },
  {
    id: "alert-dialog",
    name: "Alert Dialog",
    group: "레이어와 피드백",
    description: "중요한 작업을 실행하기 전의 확인.",
    Example: AlertDialogExample,
    primitive: true,
  },
  {
    id: "drawer",
    name: "Drawer",
    group: "레이어와 피드백",
    description: "아래에서 열리는 상세 패널.",
    Example: DrawerExample,
    primitive: true,
  },
  {
    id: "popover",
    name: "Popover",
    group: "레이어와 피드백",
    description: "Popover의 조합 가능한 사용 예제.",
    Example: PopoverExample,
    primitive: true,
  },
  {
    id: "preview-card",
    name: "Preview Card",
    group: "레이어와 피드백",
    description: "Preview Card의 조합 가능한 사용 예제.",
    Example: PreviewCardExample,
    primitive: true,
  },
  {
    id: "tooltip",
    name: "Tooltip",
    group: "레이어와 피드백",
    description: "Tooltip의 조합 가능한 사용 예제.",
    Example: TooltipExample,
    primitive: true,
  },
  {
    id: "menu",
    name: "Menu",
    group: "레이어와 피드백",
    description: "프로젝트의 관련 동작을 모아 보여줍니다.",
    Example: MenuExample,
    primitive: true,
  },
  {
    id: "context-menu",
    name: "Context Menu",
    group: "레이어와 피드백",
    description: "Context Menu의 조합 가능한 사용 예제.",
    Example: ContextMenuExample,
    primitive: true,
  },
  {
    id: "toast",
    name: "Toast",
    group: "레이어와 피드백",
    description: "작업 결과를 잠시 표시합니다.",
    Example: ToastExample,
    primitive: true,
  },
  {
    id: "accordion",
    name: "Accordion",
    group: "탐색과 구조",
    description: "Accordion의 조합 가능한 사용 예제.",
    Example: AccordionExample,
    primitive: true,
  },
  {
    id: "collapsible",
    name: "Collapsible",
    group: "탐색과 구조",
    description: "Collapsible의 조합 가능한 사용 예제.",
    Example: CollapsibleExample,
    primitive: true,
  },
  {
    id: "tabs",
    name: "Tabs",
    group: "탐색과 구조",
    description: "관련 콘텐츠 사이를 이동합니다.",
    Example: TabsExample,
    primitive: true,
  },
  {
    id: "toggle",
    name: "Toggle",
    group: "탐색과 구조",
    description: "Toggle의 조합 가능한 사용 예제.",
    Example: ToggleExample,
    primitive: true,
  },
  {
    id: "toggle-group",
    name: "Toggle Group",
    group: "탐색과 구조",
    description: "Toggle Group의 조합 가능한 사용 예제.",
    Example: ToggleGroupExample,
    primitive: true,
  },
  {
    id: "toolbar",
    name: "Toolbar",
    group: "탐색과 구조",
    description: "Toolbar의 조합 가능한 사용 예제.",
    Example: ToolbarExample,
    primitive: true,
  },
  {
    id: "menubar",
    name: "Menubar",
    group: "탐색과 구조",
    description: "Menubar의 조합 가능한 사용 예제.",
    Example: MenubarExample,
    primitive: true,
  },
  {
    id: "navigation-menu",
    name: "Navigation Menu",
    group: "탐색과 구조",
    description: "Navigation Menu의 조합 가능한 사용 예제.",
    Example: NavigationMenuExample,
    primitive: true,
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    group: "탐색과 구조",
    description: "Breadcrumb의 조합 가능한 사용 예제.",
    Example: BreadcrumbExample,
    primitive: false,
  },
  {
    id: "avatar",
    name: "Avatar",
    group: "콘텐츠 표시",
    description: "Avatar의 조합 가능한 사용 예제.",
    Example: AvatarExample,
    primitive: true,
  },
  {
    id: "badge",
    name: "Badge",
    group: "콘텐츠 표시",
    description: "Badge의 조합 가능한 사용 예제.",
    Example: BadgeExample,
    primitive: false,
  },
  {
    id: "card",
    name: "Card",
    group: "콘텐츠 표시",
    description: "Card의 조합 가능한 사용 예제.",
    Example: CardExample,
    primitive: false,
  },
  {
    id: "alert",
    name: "Alert",
    group: "콘텐츠 표시",
    description: "Alert의 조합 가능한 사용 예제.",
    Example: AlertExample,
    primitive: false,
  },
  {
    id: "progress",
    name: "Progress",
    group: "콘텐츠 표시",
    description: "Progress의 조합 가능한 사용 예제.",
    Example: ProgressExample,
    primitive: true,
  },
  {
    id: "meter",
    name: "Meter",
    group: "콘텐츠 표시",
    description: "Meter의 조합 가능한 사용 예제.",
    Example: MeterExample,
    primitive: true,
  },
  {
    id: "scroll-area",
    name: "Scroll Area",
    group: "콘텐츠 표시",
    description: "Scroll Area의 조합 가능한 사용 예제.",
    Example: ScrollAreaExample,
    primitive: true,
  },
  {
    id: "separator",
    name: "Separator",
    group: "콘텐츠 표시",
    description: "Separator의 조합 가능한 사용 예제.",
    Example: SeparatorExample,
    primitive: true,
  },
  {
    id: "skeleton",
    name: "Skeleton",
    group: "콘텐츠 표시",
    description: "Skeleton의 조합 가능한 사용 예제.",
    Example: SkeletonExample,
    primitive: false,
  },
  {
    id: "table",
    name: "Table",
    group: "콘텐츠 표시",
    description: "Table의 조합 가능한 사용 예제.",
    Example: TableExample,
    primitive: false,
  },
  {
    id: "typography",
    name: "Typography",
    group: "콘텐츠 표시",
    description: "Builder Sans와 회사 사이트의 제목 표현.",
    Example: TypographyExample,
    primitive: false,
  },
  {
    id: "empty",
    name: "Empty",
    group: "콘텐츠 표시",
    description: "Empty의 조합 가능한 사용 예제.",
    Example: EmptyExample,
    primitive: false,
  },
];
