"use client";
// Generated by pnpm examples:build. Do not edit.
import { lazy } from "react";
export const examples = {
  "accordion-multiple": lazy(() =>
    import("./accordion-multiple").then((m) => ({
      default: m.AccordionMultipleExample,
    })),
  ),
  accordion: lazy(() =>
    import("./accordion").then((m) => ({ default: m.AccordionExample })),
  ),
  "alert-dialog": lazy(() =>
    import("./alert-dialog").then((m) => ({ default: m.AlertDialogExample })),
  ),
  alert: lazy(() =>
    import("./alert").then((m) => ({ default: m.AlertExample })),
  ),
  "autocomplete-controlled": lazy(() =>
    import("./autocomplete-controlled").then((m) => ({
      default: m.AutocompleteControlledExample,
    })),
  ),
  autocomplete: lazy(() =>
    import("./autocomplete").then((m) => ({ default: m.AutocompleteExample })),
  ),
  "avatar-fallback": lazy(() =>
    import("./avatar-fallback").then((m) => ({
      default: m.AvatarFallbackExample,
    })),
  ),
  avatar: lazy(() =>
    import("./avatar").then((m) => ({ default: m.AvatarExample })),
  ),
  "badge-alert": lazy(() =>
    import("./badge-alert").then((m) => ({ default: m.BadgeAlertExample })),
  ),
  "badge-contrast": lazy(() =>
    import("./badge-contrast").then((m) => ({
      default: m.BadgeContrastExample,
    })),
  ),
  "badge-emphasis": lazy(() =>
    import("./badge-emphasis").then((m) => ({
      default: m.BadgeEmphasisExample,
    })),
  ),
  "badge-over-media": lazy(() =>
    import("./badge-over-media").then((m) => ({
      default: m.BadgeOverMediaExample,
    })),
  ),
  "badge-shape": lazy(() =>
    import("./badge-shape").then((m) => ({ default: m.BadgeShapeExample })),
  ),
  "badge-sizes": lazy(() =>
    import("./badge-sizes").then((m) => ({ default: m.BadgeSizesExample })),
  ),
  "badge-standard": lazy(() =>
    import("./badge-standard").then((m) => ({
      default: m.BadgeStandardExample,
    })),
  ),
  "badge-success": lazy(() =>
    import("./badge-success").then((m) => ({ default: m.BadgeSuccessExample })),
  ),
  "badge-warning": lazy(() =>
    import("./badge-warning").then((m) => ({ default: m.BadgeWarningExample })),
  ),
  badge: lazy(() =>
    import("./badge").then((m) => ({ default: m.BadgeExample })),
  ),
  breadcrumb: lazy(() =>
    import("./breadcrumb").then((m) => ({ default: m.BreadcrumbExample })),
  ),
  "button-alert": lazy(() =>
    import("./button-alert").then((m) => ({ default: m.ButtonAlertExample })),
  ),
  "button-disabled": lazy(() =>
    import("./button-disabled").then((m) => ({
      default: m.ButtonDisabledExample,
    })),
  ),
  "button-emphasis": lazy(() =>
    import("./button-emphasis").then((m) => ({
      default: m.ButtonEmphasisExample,
    })),
  ),
  "button-link": lazy(() =>
    import("./button-link").then((m) => ({ default: m.ButtonLinkExample })),
  ),
  "button-loading": lazy(() =>
    import("./button-loading").then((m) => ({
      default: m.ButtonLoadingExample,
    })),
  ),
  "button-over-media": lazy(() =>
    import("./button-over-media").then((m) => ({
      default: m.ButtonOverMediaExample,
    })),
  ),
  "button-overview": lazy(() =>
    import("./button-overview").then((m) => ({
      default: m.ButtonOverviewExample,
    })),
  ),
  "button-sizes": lazy(() =>
    import("./button-sizes").then((m) => ({ default: m.ButtonSizesExample })),
  ),
  "button-soft-emphasis": lazy(() =>
    import("./button-soft-emphasis").then((m) => ({
      default: m.ButtonSoftEmphasisExample,
    })),
  ),
  "button-standard": lazy(() =>
    import("./button-standard").then((m) => ({
      default: m.ButtonStandardExample,
    })),
  ),
  "button-sub-emphasis": lazy(() =>
    import("./button-sub-emphasis").then((m) => ({
      default: m.ButtonSubEmphasisExample,
    })),
  ),
  "button-subtle": lazy(() =>
    import("./button-subtle").then((m) => ({ default: m.ButtonSubtleExample })),
  ),
  "button-utility": lazy(() =>
    import("./button-utility").then((m) => ({
      default: m.ButtonUtilityExample,
    })),
  ),
  button: lazy(() =>
    import("./button").then((m) => ({ default: m.ButtonExample })),
  ),
  "card-actions": lazy(() =>
    import("./card-actions").then((m) => ({ default: m.CardActionsExample })),
  ),
  "card-asset-detail": lazy(() =>
    import("./card-asset-detail").then((m) => ({
      default: m.CardAssetDetailExample,
    })),
  ),
  "card-asset-select": lazy(() =>
    import("./card-asset-select").then((m) => ({
      default: m.CardAssetSelectExample,
    })),
  ),
  "card-asset": lazy(() =>
    import("./card-asset").then((m) => ({ default: m.CardAssetExample })),
  ),
  "card-compact": lazy(() =>
    import("./card-compact").then((m) => ({ default: m.CardCompactExample })),
  ),
  "card-fallback": lazy(() =>
    import("./card-fallback").then((m) => ({ default: m.CardFallbackExample })),
  ),
  "card-filled": lazy(() =>
    import("./card-filled").then((m) => ({ default: m.CardFilledExample })),
  ),
  "card-horizontal": lazy(() =>
    import("./card-horizontal").then((m) => ({
      default: m.CardHorizontalExample,
    })),
  ),
  "card-project": lazy(() =>
    import("./card-project").then((m) => ({ default: m.CardProjectExample })),
  ),
  "card-wide": lazy(() =>
    import("./card-wide").then((m) => ({ default: m.CardWideExample })),
  ),
  card: lazy(() => import("./card").then((m) => ({ default: m.CardExample }))),
  carousel: lazy(() =>
    import("./carousel").then((m) => ({ default: m.CarouselExample })),
  ),
  "chat-group": lazy(() =>
    import("./chat-group").then((m) => ({ default: m.ChatGroupExample })),
  ),
  chat: lazy(() => import("./chat").then((m) => ({ default: m.ChatExample }))),
  "checkbox-checked": lazy(() =>
    import("./checkbox-checked").then((m) => ({
      default: m.CheckboxCheckedExample,
    })),
  ),
  "checkbox-disabled": lazy(() =>
    import("./checkbox-disabled").then((m) => ({
      default: m.CheckboxDisabledExample,
    })),
  ),
  "checkbox-group-controlled": lazy(() =>
    import("./checkbox-group-controlled").then((m) => ({
      default: m.CheckboxGroupControlledExample,
    })),
  ),
  "checkbox-group": lazy(() =>
    import("./checkbox-group").then((m) => ({
      default: m.CheckboxGroupExample,
    })),
  ),
  "checkbox-indeterminate": lazy(() =>
    import("./checkbox-indeterminate").then((m) => ({
      default: m.CheckboxIndeterminateExample,
    })),
  ),
  "checkbox-sizes": lazy(() =>
    import("./checkbox-sizes").then((m) => ({
      default: m.CheckboxSizesExample,
    })),
  ),
  checkbox: lazy(() =>
    import("./checkbox").then((m) => ({ default: m.CheckboxExample })),
  ),
  collapsible: lazy(() =>
    import("./collapsible").then((m) => ({ default: m.CollapsibleExample })),
  ),
  "combobox-clear": lazy(() =>
    import("./combobox-clear").then((m) => ({
      default: m.ComboboxClearExample,
    })),
  ),
  "combobox-multiple": lazy(() =>
    import("./combobox-multiple").then((m) => ({
      default: m.ComboboxMultipleExample,
    })),
  ),
  combobox: lazy(() =>
    import("./combobox").then((m) => ({ default: m.ComboboxExample })),
  ),
  "context-menu": lazy(() =>
    import("./context-menu").then((m) => ({ default: m.ContextMenuExample })),
  ),
  "dialog-close": lazy(() =>
    import("./dialog-close").then((m) => ({ default: m.DialogCloseExample })),
  ),
  "dialog-lg": lazy(() =>
    import("./dialog-lg").then((m) => ({ default: m.DialogLgExample })),
  ),
  "dialog-md": lazy(() =>
    import("./dialog-md").then((m) => ({ default: m.DialogMdExample })),
  ),
  "dialog-sm": lazy(() =>
    import("./dialog-sm").then((m) => ({ default: m.DialogSmExample })),
  ),
  dialog: lazy(() =>
    import("./dialog").then((m) => ({ default: m.DialogExample })),
  ),
  drawer: lazy(() =>
    import("./drawer").then((m) => ({ default: m.DrawerExample })),
  ),
  empty: lazy(() =>
    import("./empty").then((m) => ({ default: m.EmptyExample })),
  ),
  field: lazy(() =>
    import("./field").then((m) => ({ default: m.FieldExample })),
  ),
  fieldset: lazy(() =>
    import("./fieldset").then((m) => ({ default: m.FieldsetExample })),
  ),
  form: lazy(() => import("./form").then((m) => ({ default: m.FormExample }))),
  "icon-button-alert": lazy(() =>
    import("./icon-button-alert").then((m) => ({
      default: m.IconButtonAlertExample,
    })),
  ),
  "icon-button-circular": lazy(() =>
    import("./icon-button-circular").then((m) => ({
      default: m.IconButtonCircularExample,
    })),
  ),
  "icon-button-disabled": lazy(() =>
    import("./icon-button-disabled").then((m) => ({
      default: m.IconButtonDisabledExample,
    })),
  ),
  "icon-button-emphasis": lazy(() =>
    import("./icon-button-emphasis").then((m) => ({
      default: m.IconButtonEmphasisExample,
    })),
  ),
  "icon-button-over-media": lazy(() =>
    import("./icon-button-over-media").then((m) => ({
      default: m.IconButtonOverMediaExample,
    })),
  ),
  "icon-button-selected": lazy(() =>
    import("./icon-button-selected").then((m) => ({
      default: m.IconButtonSelectedExample,
    })),
  ),
  "icon-button-sizes": lazy(() =>
    import("./icon-button-sizes").then((m) => ({
      default: m.IconButtonSizesExample,
    })),
  ),
  "icon-button-standard": lazy(() =>
    import("./icon-button-standard").then((m) => ({
      default: m.IconButtonStandardExample,
    })),
  ),
  "icon-button-utility": lazy(() =>
    import("./icon-button-utility").then((m) => ({
      default: m.IconButtonUtilityExample,
    })),
  ),
  "icon-button": lazy(() =>
    import("./icon-button").then((m) => ({ default: m.IconButtonExample })),
  ),
  "icon-custom": lazy(() =>
    import("./icon-custom").then((m) => ({ default: m.IconCustomExample })),
  ),
  icon: lazy(() => import("./icon").then((m) => ({ default: m.IconExample }))),
  "input-contrast": lazy(() =>
    import("./input-contrast").then((m) => ({
      default: m.InputContrastExample,
    })),
  ),
  "input-disabled": lazy(() =>
    import("./input-disabled").then((m) => ({
      default: m.InputDisabledExample,
    })),
  ),
  "input-invalid": lazy(() =>
    import("./input-invalid").then((m) => ({ default: m.InputInvalidExample })),
  ),
  "input-leading": lazy(() =>
    import("./input-leading").then((m) => ({ default: m.InputLeadingExample })),
  ),
  "input-readonly": lazy(() =>
    import("./input-readonly").then((m) => ({
      default: m.InputReadonlyExample,
    })),
  ),
  "input-sizes": lazy(() =>
    import("./input-sizes").then((m) => ({ default: m.InputSizesExample })),
  ),
  "input-standard": lazy(() =>
    import("./input-standard").then((m) => ({
      default: m.InputStandardExample,
    })),
  ),
  "input-trailing": lazy(() =>
    import("./input-trailing").then((m) => ({
      default: m.InputTrailingExample,
    })),
  ),
  "input-utility": lazy(() =>
    import("./input-utility").then((m) => ({ default: m.InputUtilityExample })),
  ),
  input: lazy(() =>
    import("./input").then((m) => ({ default: m.InputExample })),
  ),
  "list-action": lazy(() =>
    import("./list-action").then((m) => ({ default: m.ListActionExample })),
  ),
  "list-boxed": lazy(() =>
    import("./list-boxed").then((m) => ({ default: m.ListBoxedExample })),
  ),
  "list-inset": lazy(() =>
    import("./list-inset").then((m) => ({ default: m.ListInsetExample })),
  ),
  "list-standard": lazy(() =>
    import("./list-standard").then((m) => ({ default: m.ListStandardExample })),
  ),
  list: lazy(() => import("./list").then((m) => ({ default: m.ListExample }))),
  "menu-checkbox": lazy(() =>
    import("./menu-checkbox").then((m) => ({ default: m.MenuCheckboxExample })),
  ),
  "menu-disabled": lazy(() =>
    import("./menu-disabled").then((m) => ({ default: m.MenuDisabledExample })),
  ),
  "menu-lg": lazy(() =>
    import("./menu-lg").then((m) => ({ default: m.MenuLgExample })),
  ),
  "menu-md": lazy(() =>
    import("./menu-md").then((m) => ({ default: m.MenuMdExample })),
  ),
  "menu-radio": lazy(() =>
    import("./menu-radio").then((m) => ({ default: m.MenuRadioExample })),
  ),
  "menu-sm": lazy(() =>
    import("./menu-sm").then((m) => ({ default: m.MenuSmExample })),
  ),
  "menu-submenu": lazy(() =>
    import("./menu-submenu").then((m) => ({ default: m.MenuSubmenuExample })),
  ),
  "menu-xs": lazy(() =>
    import("./menu-xs").then((m) => ({ default: m.MenuXsExample })),
  ),
  menu: lazy(() => import("./menu").then((m) => ({ default: m.MenuExample }))),
  menubar: lazy(() =>
    import("./menubar").then((m) => ({ default: m.MenubarExample })),
  ),
  meter: lazy(() =>
    import("./meter").then((m) => ({ default: m.MeterExample })),
  ),
  motion: lazy(() =>
    import("./motion").then((m) => ({ default: m.MotionExample })),
  ),
  "navigation-item-disabled": lazy(() =>
    import("./navigation-item-disabled").then((m) => ({
      default: m.NavigationItemDisabledExample,
    })),
  ),
  "navigation-item-link": lazy(() =>
    import("./navigation-item-link").then((m) => ({
      default: m.NavigationItemLinkExample,
    })),
  ),
  "navigation-item-trailing": lazy(() =>
    import("./navigation-item-trailing").then((m) => ({
      default: m.NavigationItemTrailingExample,
    })),
  ),
  "navigation-item": lazy(() =>
    import("./navigation-item").then((m) => ({
      default: m.NavigationItemExample,
    })),
  ),
  "navigation-menu": lazy(() =>
    import("./navigation-menu").then((m) => ({
      default: m.NavigationMenuExample,
    })),
  ),
  "number-field-step": lazy(() =>
    import("./number-field-step").then((m) => ({
      default: m.NumberFieldStepExample,
    })),
  ),
  "number-field": lazy(() =>
    import("./number-field").then((m) => ({ default: m.NumberFieldExample })),
  ),
  "otp-field": lazy(() =>
    import("./otp-field").then((m) => ({ default: m.OTPExample })),
  ),
  "popover-inverse": lazy(() =>
    import("./popover-inverse").then((m) => ({
      default: m.PopoverInverseExample,
    })),
  ),
  "popover-standard": lazy(() =>
    import("./popover-standard").then((m) => ({
      default: m.PopoverStandardExample,
    })),
  ),
  popover: lazy(() =>
    import("./popover").then((m) => ({ default: m.PopoverExample })),
  ),
  "preview-card": lazy(() =>
    import("./preview-card").then((m) => ({ default: m.PreviewCardExample })),
  ),
  "progress-indeterminate": lazy(() =>
    import("./progress-indeterminate").then((m) => ({
      default: m.ProgressIndeterminateExample,
    })),
  ),
  progress: lazy(() =>
    import("./progress").then((m) => ({ default: m.ProgressExample })),
  ),
  "radio-disabled": lazy(() =>
    import("./radio-disabled").then((m) => ({
      default: m.RadioDisabledExample,
    })),
  ),
  "radio-group-controlled": lazy(() =>
    import("./radio-group-controlled").then((m) => ({
      default: m.RadioGroupControlledExample,
    })),
  ),
  "radio-group": lazy(() =>
    import("./radio-group").then((m) => ({ default: m.RadioExample })),
  ),
  radio: lazy(() =>
    import("./radio").then((m) => ({ default: m.RadioExample })),
  ),
  "scroll-area": lazy(() =>
    import("./scroll-area").then((m) => ({ default: m.ScrollAreaExample })),
  ),
  "select-controlled": lazy(() =>
    import("./select-controlled").then((m) => ({
      default: m.SelectControlledExample,
    })),
  ),
  "select-disabled": lazy(() =>
    import("./select-disabled").then((m) => ({
      default: m.SelectDisabledExample,
    })),
  ),
  "select-error": lazy(() =>
    import("./select-error").then((m) => ({ default: m.SelectErrorExample })),
  ),
  "select-form": lazy(() =>
    import("./select-form").then((m) => ({ default: m.SelectFormExample })),
  ),
  "select-lg": lazy(() =>
    import("./select-lg").then((m) => ({ default: m.SelectLgExample })),
  ),
  "select-long-list": lazy(() =>
    import("./select-long-list").then((m) => ({
      default: m.SelectLongListExample,
    })),
  ),
  "select-md": lazy(() =>
    import("./select-md").then((m) => ({ default: m.SelectMdExample })),
  ),
  "select-motion-reference": lazy(() =>
    import("./select-motion-reference").then((m) => ({
      default: m.SelectMotionReferenceExample,
    })),
  ),
  "select-motion-study": lazy(() =>
    import("./select-motion-study").then((m) => ({
      default: m.SelectMotionStudyExample,
    })),
  ),
  "select-multiple-long-labels": lazy(() =>
    import("./select-multiple-long-labels").then((m) => ({
      default: m.SelectMultipleLongLabelsExample,
    })),
  ),
  "select-multiple": lazy(() =>
    import("./select-multiple").then((m) => ({
      default: m.SelectMultipleExample,
    })),
  ),
  "select-placeholder": lazy(() =>
    import("./select-placeholder").then((m) => ({
      default: m.SelectPlaceholderExample,
    })),
  ),
  "select-readonly": lazy(() =>
    import("./select-readonly").then((m) => ({
      default: m.SelectReadonlyExample,
    })),
  ),
  "select-sizes": lazy(() =>
    import("./select-sizes").then((m) => ({ default: m.SelectSizesExample })),
  ),
  "select-sm": lazy(() =>
    import("./select-sm").then((m) => ({ default: m.SelectSmExample })),
  ),
  select: lazy(() =>
    import("./select").then((m) => ({ default: m.SelectExample })),
  ),
  "separator-vertical": lazy(() =>
    import("./separator-vertical").then((m) => ({
      default: m.SeparatorVerticalExample,
    })),
  ),
  separator: lazy(() =>
    import("./separator").then((m) => ({ default: m.SeparatorExample })),
  ),
  settings: lazy(() =>
    import("./settings").then((m) => ({ default: m.SettingsExample })),
  ),
  "sidebar-responsive": lazy(() =>
    import("./sidebar-responsive").then((m) => ({
      default: m.SidebarResponsiveExample,
    })),
  ),
  sidebar: lazy(() =>
    import("./sidebar").then((m) => ({ default: m.SidebarExample })),
  ),
  skeleton: lazy(() =>
    import("./skeleton").then((m) => ({ default: m.SkeletonExample })),
  ),
  "slider-disabled": lazy(() =>
    import("./slider-disabled").then((m) => ({
      default: m.SliderDisabledExample,
    })),
  ),
  "slider-range": lazy(() =>
    import("./slider-range").then((m) => ({ default: m.SliderRangeExample })),
  ),
  slider: lazy(() =>
    import("./slider").then((m) => ({ default: m.SliderExample })),
  ),
  "status-meter-alert": lazy(() =>
    import("./status-meter-alert").then((m) => ({
      default: m.StatusMeterAlertExample,
    })),
  ),
  "status-meter-emphasis": lazy(() =>
    import("./status-meter-emphasis").then((m) => ({
      default: m.StatusMeterEmphasisExample,
    })),
  ),
  "status-meter-success": lazy(() =>
    import("./status-meter-success").then((m) => ({
      default: m.StatusMeterSuccessExample,
    })),
  ),
  "status-meter-warning": lazy(() =>
    import("./status-meter-warning").then((m) => ({
      default: m.StatusMeterWarningExample,
    })),
  ),
  "status-meter": lazy(() =>
    import("./status-meter").then((m) => ({ default: m.StatusMeterExample })),
  ),
  "switch-controlled": lazy(() =>
    import("./switch-controlled").then((m) => ({
      default: m.SwitchControlledExample,
    })),
  ),
  "switch-disabled": lazy(() =>
    import("./switch-disabled").then((m) => ({
      default: m.SwitchDisabledExample,
    })),
  ),
  "switch-sizes": lazy(() =>
    import("./switch-sizes").then((m) => ({ default: m.SwitchSizesExample })),
  ),
  switch: lazy(() =>
    import("./switch").then((m) => ({ default: m.SwitchExample })),
  ),
  table: lazy(() =>
    import("./table").then((m) => ({ default: m.TableExample })),
  ),
  "tabs-disabled": lazy(() =>
    import("./tabs-disabled").then((m) => ({ default: m.TabsDisabledExample })),
  ),
  "tabs-manual": lazy(() =>
    import("./tabs-manual").then((m) => ({ default: m.TabsManualExample })),
  ),
  tabs: lazy(() => import("./tabs").then((m) => ({ default: m.TabsExample }))),
  "textarea-disabled": lazy(() =>
    import("./textarea-disabled").then((m) => ({
      default: m.TextareaDisabledExample,
    })),
  ),
  textarea: lazy(() =>
    import("./textarea").then((m) => ({ default: m.TextareaExample })),
  ),
  "toast-change": lazy(() =>
    import("./toast-change").then((m) => ({ default: m.ToastChangeExample })),
  ),
  "toast-description": lazy(() =>
    import("./toast-description").then((m) => ({
      default: m.ToastDescriptionExample,
    })),
  ),
  "toast-replace": lazy(() =>
    import("./toast-replace").then((m) => ({ default: m.ToastReplaceExample })),
  ),
  "toast-retry": lazy(() =>
    import("./toast-retry").then((m) => ({ default: m.ToastRetryExample })),
  ),
  "toast-undo": lazy(() =>
    import("./toast-undo").then((m) => ({ default: m.ToastUndoExample })),
  ),
  "toast-variants": lazy(() =>
    import("./toast-variants").then((m) => ({
      default: m.ToastVariantsExample,
    })),
  ),
  toast: lazy(() =>
    import("./toast").then((m) => ({ default: m.ToastExample })),
  ),
  "toggle-controlled": lazy(() =>
    import("./toggle-controlled").then((m) => ({
      default: m.ToggleControlledExample,
    })),
  ),
  "toggle-group-single": lazy(() =>
    import("./toggle-group-single").then((m) => ({
      default: m.ToggleGroupSingleExample,
    })),
  ),
  "toggle-group": lazy(() =>
    import("./toggle-group").then((m) => ({ default: m.ToggleGroupExample })),
  ),
  toggle: lazy(() =>
    import("./toggle").then((m) => ({ default: m.ToggleExample })),
  ),
  toolbar: lazy(() =>
    import("./toolbar").then((m) => ({ default: m.ToolbarExample })),
  ),
  tooltip: lazy(() =>
    import("./tooltip").then((m) => ({ default: m.TooltipExample })),
  ),
  "typography-code": lazy(() =>
    import("./typography-code").then((m) => ({
      default: m.TypographyCodeExample,
    })),
  ),
  "typography-heading": lazy(() =>
    import("./typography-heading").then((m) => ({
      default: m.TypographyHeadingExample,
    })),
  ),
  "typography-text": lazy(() =>
    import("./typography-text").then((m) => ({
      default: m.TypographyTextExample,
    })),
  ),
  typography: lazy(() =>
    import("./typography").then((m) => ({ default: m.TypographyExample })),
  ),
};
export type ExampleName = keyof typeof examples;
