import { readFileSync, writeFileSync } from "node:fs";
// Snapshot을 그대로 읽어 네임스페이스만 변경합니다. 원본 갱신은 자동 실행하지 않습니다.
const snapshot = JSON.parse(
  readFileSync(
    new URL("../tokens/roblox.snapshot.json", import.meta.url),
    "utf8",
  ),
);
const prefix = (text) => text.replace(/--(?!rbx-)/g, "--rbx-");
const block = (selector, values) =>
  `${selector} {\n${Object.entries(values)
    .map(([key, value]) => `  ${prefix(key)}: ${prefix(value)};`)
    .join("\n")}\n}\n`;
let css =
  "/* GENERATED by scripts/build-tokens.mjs. Edit tokens/roblox.snapshot.json only to update the source snapshot. Customize theme.css instead. */\n";
css += `/* Source: ${snapshot.provenance.css[0]}\nCaptured: ${snapshot.provenance.capturedAt} | SHA256: ${snapshot.provenance.foundationSha256} */\n`;
css += "@layer theme, base, components, utilities;\n@layer theme {\n";
css += block(":root", snapshot.foundation);
css += block(':root, [data-theme="light"]', snapshot.modes.light);
css += block('[data-theme="dark"]', snapshot.modes.dark);
css += "}\n";
// Default light/dark only. Classic and paid theme selectors are deliberately excluded.
writeFileSync(new URL("../src/styles/tokens.css", import.meta.url), css);
console.log(
  `Generated ${Object.keys(snapshot.foundation).length} base tokens; Default light/dark only.`,
);
